// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp8-xlRS2nxYob6MDCotxPjwNllEBb7l4',
    appId: '1:861380270348:web:0911a1cefb2b0a91b21129',
    messagingSenderId: '861380270348',
    projectId: 'my-gestor',
    authDomain: 'my-gestor.firebaseapp.com',
    storageBucket: 'my-gestor.firebasestorage.app',
    measurementId: 'G-TXQB5DT21R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBghlhfFZIGixmFuMPRt0gw91kVBq2Quno',
    appId: '1:861380270348:android:dd19067c7f07aa42b21129',
    messagingSenderId: '861380270348',
    projectId: 'my-gestor',
    storageBucket: 'my-gestor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXpxS7YIDTL3xP5oHVM59AHbEwTQzkgzQ',
    appId: '1:861380270348:ios:2ffd015ed0d75fe1b21129',
    messagingSenderId: '861380270348',
    projectId: 'my-gestor',
    storageBucket: 'my-gestor.firebasestorage.app',
    iosBundleId: 'com.webpmi.mygestor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXpxS7YIDTL3xP5oHVM59AHbEwTQzkgzQ',
    appId: '1:861380270348:ios:2ffd015ed0d75fe1b21129',
    messagingSenderId: '861380270348',
    projectId: 'my-gestor',
    storageBucket: 'my-gestor.firebasestorage.app',
    iosBundleId: 'com.webpmi.mygestor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp8-xlRS2nxYob6MDCotxPjwNllEBb7l4',
    appId: '1:861380270348:web:9ffd8d7a6321826eb21129',
    messagingSenderId: '861380270348',
    projectId: 'my-gestor',
    authDomain: 'my-gestor.firebaseapp.com',
    storageBucket: 'my-gestor.firebasestorage.app',
    measurementId: 'G-VQSG3CVCTG',
  );
}
